/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2020 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

/*
 * OpenOCD Debugger and Semi-hosting
 *
 * Set the linker arguments:
 * 	. -specs=rdimon.specs -lc -lrdimon
 *
 * Add semi-hosting run command:
 * 	. monitor arm semihosting enable
 *
 * Add the below function call to main.c
 * 	. extern void initialise_monitor_handles(void);
 * 	. initialise_monitor_handles(void);
 */

#include <stdio.h>

extern void initialise_monitor_handles(void);

int main(void)
{
	initialise_monitor_handles();

	printf("Hello World\n");

	for(;;);
}
