/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2020 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

/*
 *  Notes about MCU Bus Interfaces
 *
 *  Bus interfaces from Processor to AHB-Lite Bus Matrix
 * 	I-BUS : Instruction Bus
 * 	D-BUS : Data Bus
 * 	S-BUS : System Bus
 *
 * 	example:
 *  //A string literal (constant data) is stored in ROM (Flash Memory)
 *  const char *pMessage = "Hello World!";
 *
 *  //This is constant data. This data will be stored in ROM (Flash Memory)
 *  const int value = 200;
 *
 *  //This is not constant data. This will be stored in SRAM.
 *  char myData[50];
 *
 *  int main(void)
 *  {
 *  	for(uint32_t i = 0; i < strlen(pMessage); i++)
 *  	{
 *  		//This is data copy from FLASH to SRAM
 *  		myData[i] = *(pMessage + i);
 *  	}
 *  	for(;;);
 *  }
 *
 *
 *  Flash memory (512kB) can be broken up into:
 *     Instructions              (fetched over I-Bus from ARM CM4 processor)
 *     Const Data (R_only)       (fetched over D-Bus from ARM CM4 processor)
 *     Vector tables             (fetched over S-Bus from ARM CM4 processor)
 *
 *	ICode Memory Interface:
 *	Instruction fetches from Code memory space, 0x00000000 to 0x1FFFFFFC, are performed over the 32-bit AHB-Lite bus.
 *	The debugger cannot access this interface. All fetches are word-wide. The number of instructions fetched per word depends
 *	on the code running and the alignment of the code in memory.
 *
 *	DCode Memory Interface:
 *	Data and debug accesses to Code memory space, 0x00000000 to 0x1FFFFFFF, are performed over the 32-bit AHB-Lite bus.
 *	The Code memory space avail is dependent on implementation. Core data accesses have a higher prio than debug accesses on this bus.
 *	This means that debug accesses are waited until core accesses have completed when there are simultaneous core and debug access to this bus.
 *
 *	System Interface
 *	Instruction fetches and data and debug accesses to address ranges 0x20000000 to 0xDFFFFFFF and 0xE0100000 to 0xFFFFFFFF are performed over the
 *	32-bit AHB-Lite bus.
 *	For simultaneous accesses to 32-bit AHB-Lite bus, the arbitration order in decreasing priority is:
 *		Data Accesses
 *		Instruction and vector fetches
 *		Debug
 *	The system bus interface contains control logic to handle unaligned accesses, FPB remapped accesses, bit-band accesses and pipelined instruction fetches.
 *
 *	Summary:
 *	If the instructions are present in between the memory locations 0x00000000 to 0x1FFFFFFC then the Cortex Processor will fetch the instructions using
 *	I-CODE interface.
 *	If the instructions are present outside of 0x00000000 to 0x1FFFFFFC then processor fetches the instructions over the system bus.
 *
 *	If the data is present in between memory locations 0x00000000 to 0x1FFFFFFF then the processor fetches the data over D-CODE bus interface.
 *	If the data is present outside 0x00000000 to 0x1FFFFFFF then the data will be fetched over the system bus.
 *
 *	FLASH is connected to ICODE and DCODE only, not System Bus.
 *
 *  System Bus talks to peripherals.
 *
 *  System Bus can operate at 180MHz (Cortex M4)
 *
 *  AHB-Lite Bus Matrix interfaces with AHB1 (180MHz) and AHB2 (180MHz) system buses.
 *
 *  AHB1 Bus (180MHz) meets a bridge that selects/converts between APB1 (45MHz) and APB2 (90MHz) buses that interface with different peripherals.
 *
 *  Processor cannot fetch instructions and data simultaneously from SRAM because thats connected to the System Bus.
 *  Processor can however fetch instructions and data simultaneously from FLASH because it can utilize both ICODE and DCODE.
 *
 *	System bus can only communicate with one peripheral at a time, regardless if they are on separate AHB1/2 buses.
 *	Processor can talk to SRAM and FLASH simultaneously because I-BUS, D-BUS and S-BUS are all independent.
 *
 */

int main(void)
{
    /* Loop forever */
	for(;;);
}
