/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2020 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

/*
 * 		Clocks:
 * 	Three different clock sources can be used to drive the system clock (SYSCLK):
 * 	. HSI oscillator clock
 * 	. HSE oscillator clock
 * 	. Main PLL (PLL) clock
 *
 * 	The devices have the two following secondary clock sources:
 * 	. 32kHz low-speed internal RC (LSI RC) which drives the independent watchdog and, optionally, the RTC used for Auto-wakeup from the stop/standby mode.
 * 	. 32.768 kHz low-speed external crystal (LSE crystal) which optionally drives the RTC clock (RTCCLK)
 *
 *	Sources:
 *	. Crystal Oscillator (external)
 *	. RC Oscillator (internal)
 *	. The PLL (Phase Locked Loop) (internal)
 *
 *	HSI is assumed to be default on reset.
 *
 */


int main(void)
{
    /* Loop forever */
	for(;;);
}
