/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2020 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


/*
 *		Memory Map of the MCU (STM32F446RE)
 *	ARM Cortex M4
 *	Width of the system bus is 32 bits.
 *	The processor can produce 2^32 of different addresses (4,294,967,296 addresses)
 *
 *	0x0000_0000 to 0xFFFF_FFFF
 *
 *	MCU: STM32F447X
 *
 *	1. Whats the base address of AHB1 BUS peripheral registers?
 *	AHB1_PERI_START_ADDRESS = 0x40020000;
 *	AHB1_PERI_END_ADDRESS = 0x4007FFFF;
 *
 *	2. Whats the base address of GPIOA registers?
 *	GPIOA_PERI_START_ADDRESS = AHB1_PERI_START_ADDRESS;
 *	GPIOA_PERI_END_ADDRESS = 0x400203FF;
 *
 *	3. Whats the base address of RCC engine registers of the MCU?
 *	RCC_PERI_START_ADDRESS = 0x40023800;
 *	RCC_PERI_END_ADDRESS = 0x40023BFF;
 *
 *	4. Whats the base address of APB1 peripheral registers
 *	APB1_PERI_START_ADDRESS = 0x40000000;
 *	APB1_PERI_END_ADDRESS = 0x40007FFF;
 *
 *	5. Whats the base address of FLASH memory?
 *	FLASH_START_ADDRESS = 0x08000000;
 *	FLASH_END_ADDRESS = 0x081FFFFF;
 *
 *	6. Whats the base address of SRAM2?
 *	SRAM1 is 112kB, SRAM2 is 16kB
 *	SRAM1 starts at 0x20000000
 *	base address of SRAM2 = 0x2001C000
 *
 *	BASE_ADDRESS_OF_SRAM = 0x20000000;
 *	SIZE_OF_SRAM1 = 0x0001BFFF;
 *	BASE_ADDRESS_OF_SRAM2 = ((BASE_ADDRESS_OF_SRAM + SIZE_OF_SRAM1) + 1);
 *
 *	7. Whats the base address of ADC registers?
 *	ADC_START_ADDRESS = 0x40012000;
 *	ADC_END_ADDRESS = 0x400123FF;
 *
 *
 *
 *
 *
 *
 *
 *
 */


int main(void)
{

	for(;;);
}
