/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2020 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */


/*
 * Peripheral Clock configuration
 * . In modern MCUs, before using any peripheral, you must enable its peripheral clock using peripheral clock registers.
 * . By default, peripheral clocks of most all peripherals will be disabled to save power.
 * . A peripheral wont take or respond to your configuration values until you enable its peripheral clock.
 * . In STM32 microcontrollers, peripheral clocks are managed through RCC registers.
 *
 *	Before you configure any peripheral register, you must enable its clock first **IMPORTANT**
 *
 *
 */


#include <stdint.h>

#define ADC_BASE_ADDR 		0x40012000UL
#define ADC_CR1_REG_OFFSET 	0x04UL
#define ADC_CR1_REG_ADDR 	(ADC_BASE_ADDR + ADC_CR1_REG_OFFSET)

#define RCC_BASE_ADDR		0x40023800UL
#define RCC_APB2_ENR_OFFSET	0x44UL
#define RCC_APB2_ENR_ADDR	(RCC_BASE_ADDR + RCC_APB2_ENR_OFFSET)

int main(void)
{
    uint32_t *pAdcCr1Reg =  (uint32_t*) ADC_CR1_REG_ADDR;
	uint32_t *pRccApb2Enr = (uint32_t*) RCC_APB2_ENR_ADDR;

    //1. Enable the peripheral clock for ADC1
	*pRccApb2Enr |= (1 << 8);

	//2. Modify the ADC CR1 register
    *pAdcCr1Reg |= (1 << 8);

	for(;;);
}
